name: Golang Setup runner
on:
  push:
    branches: [ "main" ]
    paths-ignore: [
      "README.md",
      ".gitignore",
      "LICENSE",
      "**/*.mod",
      "**/*.sum",
    ]

jobs:
  Build:
    runs-on: ${{ matrix.runner }}
    strategy:
      matrix:
        runner: [ubuntu-latest]
        go-ver: [ '1.21.x', '1.22.x', '1.23.x', '1.24.x' ]

    steps:
      - uses: actions/checkout@v4.2.2
      
      - name: Setup Go ${{ matrix.go-ver }}
        uses: actions/setup-go@v5.3.0
        with:
          go-version: ${{ matrix.go-ver }}

      - name: Show Golang version
        run: |
          go version

  Test:
    runs-on: ${{ matrix.runner }}
    steps:
      - uses: actions/checkout@v4.2.2
      
      - name: Setup Go
        uses: actions/setup-go@v5.3.0
        with:
          go-version: ${{ matrix.go-ver }}

      - name: Run tests
        run: |
          go test -v ./tests/...